// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type Artist struct {
	ID       int64
	Name     string
	DjName   string
	Label    sql.NullString
	Location sql.NullString
	Region   sql.NullString
	Genre    string
	Link     sql.NullString
}

type Genre struct {
	ID   int64
	Name string
}

type GenreLink struct {
	ID          int64
	GenreID     int64
	HistoryLink string
}

type Label struct {
	ID       int64
	Name     string
	Location sql.NullString
	Region   string
	Genre    string
	Link     sql.NullString
}

type Venue struct {
	ID       int64
	Name     string
	Location string
	Region   string
	Link     sql.NullString
}
