// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
)

const getArtistByID = `-- name: GetArtistByID :one
SELECT id, name, dj_name, label, location, region, genre, link
FROM artists
WHERE id = ? LIMIT 1
`

func (q *Queries) GetArtistByID(ctx context.Context, id int64) (Artist, error) {
	row := q.db.QueryRowContext(ctx, getArtistByID, id)
	var i Artist
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DjName,
		&i.Label,
		&i.Location,
		&i.Region,
		&i.Genre,
		&i.Link,
	)
	return i, err
}

const getGenreByID = `-- name: GetGenreByID :one
SELECT id, name
FROM genres
WHERE id = ? LIMIT 1
`

func (q *Queries) GetGenreByID(ctx context.Context, id int64) (Genre, error) {
	row := q.db.QueryRowContext(ctx, getGenreByID, id)
	var i Genre
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getLabelByID = `-- name: GetLabelByID :one
SELECT id, name, location, region, genre, link
FROM labels
WHERE id = ? LIMIT 1
`

func (q *Queries) GetLabelByID(ctx context.Context, id int64) (Label, error) {
	row := q.db.QueryRowContext(ctx, getLabelByID, id)
	var i Label
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Location,
		&i.Region,
		&i.Genre,
		&i.Link,
	)
	return i, err
}

const getVenueByID = `-- name: GetVenueByID :one
SELECT id, name, location, region, link
FROM venues
WHERE id = ? LIMIT 1
`

func (q *Queries) GetVenueByID(ctx context.Context, id int64) (Venue, error) {
	row := q.db.QueryRowContext(ctx, getVenueByID, id)
	var i Venue
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Location,
		&i.Region,
		&i.Link,
	)
	return i, err
}

const listArtists = `-- name: ListArtists :many
SELECT id, name, dj_name, label, location, region, genre, link
FROM artists
WHERE (? = '' OR name = ?)
`

type ListArtistsParams struct {
	Column1 interface{}
	Name    string
}

func (q *Queries) ListArtists(ctx context.Context, arg ListArtistsParams) ([]Artist, error) {
	rows, err := q.db.QueryContext(ctx, listArtists, arg.Column1, arg.Name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Artist
	for rows.Next() {
		var i Artist
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DjName,
			&i.Label,
			&i.Location,
			&i.Region,
			&i.Genre,
			&i.Link,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGenres = `-- name: ListGenres :many
SELECT id, name
FROM genres
WHERE (? = '' OR name = ?)
`

type ListGenresParams struct {
	Column1 interface{}
	Name    string
}

func (q *Queries) ListGenres(ctx context.Context, arg ListGenresParams) ([]Genre, error) {
	rows, err := q.db.QueryContext(ctx, listGenres, arg.Column1, arg.Name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Genre
	for rows.Next() {
		var i Genre
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLabels = `-- name: ListLabels :many
SELECT id, name, location, region, genre, link
FROM labels
WHERE (? = '' OR name = ?)
`

type ListLabelsParams struct {
	Column1 interface{}
	Name    string
}

func (q *Queries) ListLabels(ctx context.Context, arg ListLabelsParams) ([]Label, error) {
	rows, err := q.db.QueryContext(ctx, listLabels, arg.Column1, arg.Name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Label
	for rows.Next() {
		var i Label
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Location,
			&i.Region,
			&i.Genre,
			&i.Link,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVenues = `-- name: ListVenues :many
SELECT id, name, location, region, link
FROM venues
WHERE (? = '' OR name = ?)
`

type ListVenuesParams struct {
	Column1 interface{}
	Name    string
}

func (q *Queries) ListVenues(ctx context.Context, arg ListVenuesParams) ([]Venue, error) {
	rows, err := q.db.QueryContext(ctx, listVenues, arg.Column1, arg.Name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Venue
	for rows.Next() {
		var i Venue
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Location,
			&i.Region,
			&i.Link,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
